package provider

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/Fluent-Health/terraform-provider-medplum/internal/client"
)

func NewClientApplicationResource() resource.Resource { return &clientApplicationResource{} }

type clientApplicationResource struct{ data *providerData }

type clientApplicationModel struct {
	ID               types.String           `tfsdk:"id"`
	Name             types.String           `tfsdk:"name"`
	Description      types.String           `tfsdk:"description"`
	RedirectURI      types.String           `tfsdk:"redirect_uri"`
	Secret           types.String           `tfsdk:"secret"`
	IdentityProvider *identityProviderModel `tfsdk:"identity_provider"`
}

type identityProviderModel struct {
	AuthorizeURL types.String `tfsdk:"authorize_url"`
	TokenURL     types.String `tfsdk:"token_url"`
	UserInfoURL  types.String `tfsdk:"user_info_url"`
	ClientID     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	UseSubject   types.Bool   `tfsdk:"use_subject"`
}

func (r *clientApplicationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_client_application"
}

func (r *clientApplicationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "A Medplum ClientApplication. Access is granted separately via medplum_project_membership (accessPolicy lives on the membership).",
		Attributes: map[string]schema.Attribute{
			"id":           schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"name":         schema.StringAttribute{Required: true},
			"description":  schema.StringAttribute{Optional: true},
			"redirect_uri": schema.StringAttribute{Optional: true},
			"secret": schema.StringAttribute{
				Optional: true, Computed: true, Sensitive: true,
				MarkdownDescription: "Client secret. Generated by the provider if not set.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
		Blocks: map[string]schema.Block{
			"identity_provider": schema.SingleNestedBlock{
				MarkdownDescription: "External OIDC identity provider for token exchange.",
				Attributes: map[string]schema.Attribute{
					"authorize_url": schema.StringAttribute{Optional: true},
					"token_url":     schema.StringAttribute{Optional: true},
					"user_info_url": schema.StringAttribute{Optional: true},
					"client_id":     schema.StringAttribute{Optional: true},
					"client_secret": schema.StringAttribute{Optional: true, Sensitive: true},
					"use_subject":   schema.BoolAttribute{Optional: true},
				},
			},
		},
	}
}

func (r *clientApplicationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d, ok := req.ProviderData.(*providerData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.data = d
}

// generateClientSecret mints a client secret provider-side. NOTE: Medplum's
// $rotate-secret operation cannot mint an INITIAL secret (it requires the
// current secret to match), and we deliberately avoid the admin /client
// endpoint (it would create a hidden ProjectMembership). So the provider
// generates the secret and sets it on the FHIR resource at create time.
func generateClientSecret() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

func (m clientApplicationModel) toFHIR(id, secret string) ([]byte, error) {
	doc := map[string]any{"resourceType": "ClientApplication", "name": m.Name.ValueString()}
	if secret != "" {
		doc["secret"] = secret
	}
	if id != "" {
		doc["id"] = id
	}
	if v := strOrEmpty(m.Description); v != "" {
		doc["description"] = v
	}
	if v := strOrEmpty(m.RedirectURI); v != "" {
		doc["redirectUri"] = v
	}
	if ip := m.IdentityProvider; ip != nil {
		ipDoc := map[string]any{}
		if v := strOrEmpty(ip.AuthorizeURL); v != "" {
			ipDoc["authorizeUrl"] = v
		}
		if v := strOrEmpty(ip.TokenURL); v != "" {
			ipDoc["tokenUrl"] = v
		}
		if v := strOrEmpty(ip.UserInfoURL); v != "" {
			ipDoc["userInfoUrl"] = v
		}
		if v := strOrEmpty(ip.ClientID); v != "" {
			ipDoc["clientId"] = v
		}
		if v := strOrEmpty(ip.ClientSecret); v != "" {
			ipDoc["clientSecret"] = v
		}
		if !ip.UseSubject.IsNull() && !ip.UseSubject.IsUnknown() {
			ipDoc["useSubject"] = ip.UseSubject.ValueBool()
		}
		doc["identityProvider"] = ipDoc
	}
	return json.Marshal(doc)
}

func (m *clientApplicationModel) fromFHIR(body []byte) error {
	var doc struct {
		ID               string `json:"id"`
		Name             string `json:"name"`
		Description      string `json:"description"`
		RedirectURI      string `json:"redirectUri"`
		Secret           string `json:"secret"`
		IdentityProvider *struct {
			AuthorizeURL string `json:"authorizeUrl"`
			TokenURL     string `json:"tokenUrl"`
			UserInfoURL  string `json:"userInfoUrl"`
			ClientID     string `json:"clientId"`
			ClientSecret string `json:"clientSecret"`
			UseSubject   *bool  `json:"useSubject"`
		} `json:"identityProvider"`
	}
	if err := json.Unmarshal(body, &doc); err != nil {
		return err
	}
	m.ID = types.StringValue(doc.ID)
	m.Name = types.StringValue(doc.Name)
	m.Description = optString(doc.Description)
	m.RedirectURI = optString(doc.RedirectURI)
	m.Secret = types.StringValue(doc.Secret)
	if doc.IdentityProvider != nil {
		ip := doc.IdentityProvider
		useSubject := types.BoolNull()
		if ip.UseSubject != nil {
			useSubject = types.BoolValue(*ip.UseSubject)
		}
		m.IdentityProvider = &identityProviderModel{
			AuthorizeURL: optString(ip.AuthorizeURL),
			TokenURL:     optString(ip.TokenURL),
			UserInfoURL:  optString(ip.UserInfoURL),
			ClientID:     optString(ip.ClientID),
			ClientSecret: optString(ip.ClientSecret),
			UseSubject:   useSubject,
		}
	} else {
		m.IdentityProvider = nil
	}
	return nil
}

func (r *clientApplicationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var m clientApplicationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	secret := strOrEmpty(m.Secret)
	if secret == "" {
		var err error
		secret, err = generateClientSecret()
		if err != nil {
			resp.Diagnostics.AddError("Secret generation failed", err.Error())
			return
		}
	}
	body, err := m.toFHIR("", secret)
	if err != nil {
		resp.Diagnostics.AddError("Encoding failed", err.Error())
		return
	}
	out, err := r.data.Client.FHIRCreate(ctx, "ClientApplication", body)
	if err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	if err := m.fromFHIR(out); err != nil {
		resp.Diagnostics.AddError("Decoding failed", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}

func (r *clientApplicationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var m clientApplicationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, err := r.data.Client.FHIRRead(ctx, "ClientApplication", m.ID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	if err := m.fromFHIR(out); err != nil {
		resp.Diagnostics.AddError("Decoding failed", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}

func (r *clientApplicationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state clientApplicationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Preserve the existing secret unless the user explicitly set a new one.
	secret := strOrEmpty(plan.Secret)
	if secret == "" {
		secret = state.Secret.ValueString()
	}
	body, err := plan.toFHIR(state.ID.ValueString(), secret)
	if err != nil {
		resp.Diagnostics.AddError("Encoding failed", err.Error())
		return
	}
	out, err := r.data.Client.FHIRUpdate(ctx, "ClientApplication", state.ID.ValueString(), body)
	if err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	if err := plan.fromFHIR(out); err != nil {
		resp.Diagnostics.AddError("Decoding failed", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *clientApplicationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var m clientApplicationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.data.Client.FHIRDelete(ctx, "ClientApplication", m.ID.ValueString()); err != nil && !client.IsNotFound(err) {
		resp.Diagnostics.AddError("Delete failed", err.Error())
	}
}

func (r *clientApplicationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}

var (
	_ resource.Resource                = (*clientApplicationResource)(nil)
	_ resource.ResourceWithConfigure   = (*clientApplicationResource)(nil)
	_ resource.ResourceWithImportState = (*clientApplicationResource)(nil)
)
